/**
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║       NEXUS CLAIRE — TOOL FACTORY v1.0                          ║
 * ║       Autonomous Tool Creation from AI-Generated Specs          ║
 * ╚══════════════════════════════════════════════════════════════════╝
 *
 * Adapted from OpenClaw's definePluginEntry() + api.registerTool() pattern.
 * Allows Nexus to create tools at runtime from JSON specifications
 * generated by the Architect.
 *
 * Flow:
 *   1. Architect detects repeated task pattern
 *   2. Generates a ToolSpec (JSON with name, description, parameters, logic)
 *   3. Factory validates the spec (no circular deps, unique name, valid params)
 *   4. Factory creates an executable ToolDefinition
 *   5. Registry hot-loads the new tool
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";
import { toolRegistry, type ToolDefinition, type ToolParameter } from "./tool-registry";

/* ─── Tool Spec: What the AI generates ─── */

export interface ToolSpec {
    name: string;              // e.g. "weather_lookup"
    description: string;       // What this tool does
    category?: string;         // Tool category
    parameters: Record<string, {
        type: 'string' | 'number' | 'boolean';
        description: string;
        required?: boolean;
        default?: any;
    }>;
    logic: ToolLogic;          // What happens when executed
    triggers?: string[];       // Keywords that suggest using this tool
    version?: string;
}

/**
 * ToolLogic: Defines what the tool does when executed.
 * Supports multiple execution strategies (safe, sandboxed).
 */
export type ToolLogic =
    | { type: 'http_fetch'; url: string; method?: string; headers?: Record<string, string>; bodyTemplate?: string }
    | { type: 'shell_command'; command: string; timeout?: number }
    | { type: 'transform'; inputField: string; template: string }
    | { type: 'composite'; steps: Array<{ tool: string; params: Record<string, string> }> };

/* ─── Validation Result ─── */

export interface ToolSpecValidation {
    valid: boolean;
    errors: string[];
    warnings: string[];
}

/* ─── Factory ─── */

export class NexusToolFactory {
    private learnedDir: string;
    private specLog: Array<{ spec: ToolSpec; createdAt: number; success: boolean }> = [];

    constructor() {
        this.learnedDir = join(process.cwd(), "learned-skills", "tools");
        if (!existsSync(this.learnedDir)) {
            mkdirSync(this.learnedDir, { recursive: true });
        }
    }

    /**
     * Validate a tool spec before creating it.
     * Adapted from OpenClaw's conflict detection + parameter validation.
     */
    public validate(spec: ToolSpec): ToolSpecValidation {
        const errors: string[] = [];
        const warnings: string[] = [];

        // 1. Name validation
        if (!spec.name || spec.name.length < 2) {
            errors.push("Tool name must be at least 2 characters.");
        }
        if (!/^[a-z][a-z0-9_.]*$/.test(spec.name)) {
            errors.push("Tool name must be lowercase alphanumeric with dots/underscores only.");
        }

        // 2. Conflict check — cannot overwrite existing core tools
        const existing = toolRegistry.getTool(spec.name);
        if (existing && existing.provenance === 'core') {
            errors.push(`Tool "${spec.name}" already exists as a core tool and cannot be overwritten.`);
        }

        // 3. Description validation
        if (!spec.description || spec.description.length < 10) {
            errors.push("Tool description must be at least 10 characters.");
        }

        // 4. Parameters validation
        if (spec.parameters) {
            for (const [paramName, paramDef] of Object.entries(spec.parameters)) {
                if (!['string', 'number', 'boolean'].includes(paramDef.type)) {
                    errors.push(`Parameter "${paramName}" has invalid type: ${paramDef.type}`);
                }
                if (!paramDef.description || paramDef.description.length < 3) {
                    warnings.push(`Parameter "${paramName}" has a very short description.`);
                }
            }
        }

        // 5. Logic validation
        if (!spec.logic) {
            errors.push("Tool must have a logic definition.");
        } else {
            switch (spec.logic.type) {
                case 'http_fetch':
                    if (!spec.logic.url) errors.push("HTTP fetch tools must have a URL.");
                    if (spec.logic.url && !spec.logic.url.startsWith('http')) {
                        errors.push("HTTP fetch URL must start with http:// or https://");
                    }
                    break;
                case 'shell_command':
                    if (!spec.logic.command) errors.push("Shell command tools must have a command.");
                    // Warn about dangerous commands
                    const dangerous = ['rm -rf', 'sudo', 'mkfs', 'dd if=', 'chmod 777'];
                    for (const d of dangerous) {
                        if (spec.logic.command.includes(d)) {
                            warnings.push(`Shell command contains dangerous pattern: "${d}"`);
                        }
                    }
                    break;
                case 'transform':
                    if (!spec.logic.template) errors.push("Transform tools must have a template.");
                    break;
                case 'composite':
                    if (!spec.logic.steps || spec.logic.steps.length === 0) {
                        errors.push("Composite tools must have at least one step.");
                    }
                    // Check for circular references
                    for (const step of spec.logic.steps || []) {
                        if (step.tool === spec.name) {
                            errors.push(`Circular reference detected: tool "${spec.name}" references itself.`);
                        }
                    }
                    break;
            }
        }

        return { valid: errors.length === 0, errors, warnings };
    }

    /**
     * Create a tool from a spec and register it.
     * Adapted from OpenClaw's definePluginEntry({ register(api) { api.registerTool(...) } }).
     */
    public createFromSpec(spec: ToolSpec): { success: boolean; errors?: string[]; tool?: ToolDefinition } {
        // Validate first
        const validation = this.validate(spec);
        if (!validation.valid) {
            console.error(`[TOOL FACTORY] ❌ Validation failed for "${spec.name}":`, validation.errors);
            this.specLog.push({ spec, createdAt: Date.now(), success: false });
            return { success: false, errors: validation.errors };
        }

        if (validation.warnings.length > 0) {
            console.warn(`[TOOL FACTORY] ⚠️ Warnings for "${spec.name}":`, validation.warnings);
        }

        // Build parameters map
        const params: Record<string, ToolParameter> = {};
        for (const [name, def] of Object.entries(spec.parameters)) {
            params[name] = {
                type: def.type,
                description: def.description,
                required: def.required !== false,
                default: def.default,
            };
        }

        // Build execute function based on logic type
        const executeFn = this.buildExecuteFunction(spec);

        const tool: ToolDefinition = {
            name: spec.name,
            description: spec.description,
            category: (spec.category || 'custom') as any,
            parameters: params,
            execute: executeFn,
            provenance: 'learned',
            riskLevel: this.inferRiskLevel(spec),
            timeout: spec.logic.type === 'http_fetch' ? 15000 : 30000,
            version: spec.version || '1.0.0',
            author: 'nexus',
            createdAt: Date.now(),
            useCount: 0,
        };

        // Register in the live registry
        const registered = toolRegistry.register(tool);
        if (!registered) {
            return { success: false, errors: ['Registration failed (conflict or other issue).'] };
        }

        // Persist to disk for hot-reload survival
        this.persistSpec(spec);

        this.specLog.push({ spec, createdAt: Date.now(), success: true });
        console.log(`[TOOL FACTORY] 🧬 Created new tool: "${spec.name}" (${spec.logic.type})`);

        return { success: true, tool };
    }

    /**
     * Build the execute function for a tool based on its logic type.
     */
    private buildExecuteFunction(spec: ToolSpec): ToolDefinition['execute'] {
        switch (spec.logic.type) {
            case 'http_fetch':
                return async (params: Record<string, any>) => {
                    try {
                        let url = spec.logic.type === 'http_fetch' ? (spec.logic as any).url : '';
                        const method = (spec.logic as any).method || 'GET';
                        const headers = (spec.logic as any).headers || {};

                        // Template substitution: replace {{param}} with actual values
                        for (const [key, value] of Object.entries(params)) {
                            url = url.replace(`{{${key}}}`, encodeURIComponent(String(value)));
                        }

                        const response = await fetch(url, {
                            method,
                            headers: { 'Content-Type': 'application/json', ...headers },
                            body: method !== 'GET' && (spec.logic as any).bodyTemplate
                                ? this.renderTemplate((spec.logic as any).bodyTemplate, params)
                                : undefined,
                        });

                        if (!response.ok) {
                            return `HTTP Error ${response.status}: ${response.statusText}`;
                        }

                        const text = await response.text();
                        // Truncate very long responses
                        return text.length > 5000 ? text.substring(0, 5000) + "\n... (truncated)" : text;
                    } catch (e: any) {
                        return `Error: ${e.message}`;
                    }
                };

            case 'shell_command':
                return async (params: Record<string, any>) => {
                    try {
                        const { spawnSync } = await import("bun");
                        let command = (spec.logic as any).command;

                        // Template substitution
                        for (const [key, value] of Object.entries(params)) {
                            // Sanitize for shell safety
                            const sanitized = String(value).replace(/[;&|`$(){}]/g, '');
                            command = command.replace(`{{${key}}}`, sanitized);
                        }

                        const result = spawnSync(["sh", "-c", command], {
                            timeout: (spec.logic as any).timeout || 30000,
                        });

                        const stdout = result.stdout.toString();
                        const stderr = result.stderr.toString();
                        return stdout + (stderr ? `\n[STDERR] ${stderr}` : "");
                    } catch (e: any) {
                        return `Error: ${e.message}`;
                    }
                };

            case 'transform':
                return async (params: Record<string, any>) => {
                    try {
                        return this.renderTemplate((spec.logic as any).template, params);
                    } catch (e: any) {
                        return `Error: ${e.message}`;
                    }
                };

            case 'composite':
                return async (params: Record<string, any>) => {
                    const results: string[] = [];
                    for (const step of (spec.logic as any).steps) {
                        const stepTool = toolRegistry.getTool(step.tool);
                        if (!stepTool) {
                            results.push(`[Step ${step.tool}] Error: Tool not found.`);
                            continue;
                        }

                        // Resolve step params from parent params
                        const resolvedParams: Record<string, any> = {};
                        for (const [key, value] of Object.entries(step.params)) {
                            resolvedParams[key] = params[value as string] ?? value;
                        }

                        const result = await toolRegistry.executeTool(step.tool, resolvedParams, { agentId: 'factory-composite' });
                        results.push(`[${step.tool}] ${result}`);
                    }
                    return results.join('\n');
                };

            default:
                return async () => `Error: Unknown logic type.`;
        }
    }

    /**
     * Simple template renderer: replaces {{key}} with params[key].
     */
    private renderTemplate(template: string, params: Record<string, any>): string {
        let result = template;
        for (const [key, value] of Object.entries(params)) {
            result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), String(value));
        }
        return result;
    }

    /**
     * Infer risk level from a tool spec.
     */
    private inferRiskLevel(spec: ToolSpec): 'safe' | 'moderate' | 'dangerous' {
        if (spec.logic.type === 'shell_command') return 'moderate';
        if (spec.logic.type === 'http_fetch') return 'safe';
        if (spec.logic.type === 'transform') return 'safe';
        if (spec.logic.type === 'composite') return 'moderate';
        return 'safe';
    }

    /**
     * Persist a tool spec to disk for hot-reload survival.
     */
    private persistSpec(spec: ToolSpec): void {
        try {
            const filePath = join(this.learnedDir, `${spec.name}.json`);
            writeFileSync(filePath, JSON.stringify(spec, null, 2), 'utf8');
        } catch (e: any) {
            console.warn(`[TOOL FACTORY] Failed to persist spec: ${e.message}`);
        }
    }

    /**
     * Load all persisted tool specs from disk on startup.
     */
    public loadPersistedTools(): number {
        if (!existsSync(this.learnedDir)) return 0;

        let loaded = 0;
        const entries = readdirSync(this.learnedDir);

        for (const entry of entries) {
            if (!entry.endsWith('.json')) continue;

            try {
                const filePath = join(this.learnedDir, entry);
                const spec: ToolSpec = JSON.parse(readFileSync(filePath, 'utf8'));
                const result = this.createFromSpec(spec);
                if (result.success) loaded++;
            } catch (e: any) {
                console.warn(`[TOOL FACTORY] Failed to load ${entry}: ${e.message}`);
            }
        }

        if (loaded > 0) {
            console.log(`[TOOL FACTORY] 📦 Loaded ${loaded} persisted tool(s) from disk.`);
        }
        return loaded;
    }

    /**
     * Get the creation log for diagnostics.
     */
    public getLog(): typeof this.specLog {
        return [...this.specLog];
    }
}

export const toolFactory = new NexusToolFactory();
